name: Tests Pipeline
on: [push, pull_request]
env:
    PHPUNIT_FLAGS: "--filter=Api --stop-on-failure"
jobs:
  laravel:
    name: Tests Pipeline (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.5']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP, with Composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, dom, fileinfo, mysql
          coverage: none
      - name: Install Composer dependencies
        run: composer install -q --no-progress --prefer-dist --optimize-autoloader
      - name: Prepare environment
        run: cp .env.example .env
      - name: Clear config cache
        run: php artisan config:clear
      - name: Generate key
        run: php artisan key:generate -q -n
      - name: Migrate & seed database
        run: php artisan migrate --seed --force --no-interaction
      - name: Change directory permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Install JavaScript packages
        run: yarn install --silent --no-progress
      - name: Build JavaScript packages
        run: yarn build
      - name: Run Laravel server
        run: php artisan serve --port=8000 --no-reload &
      - name: Curl to localhost
        run: curl localhost:8000 &
      - name: Run tests
        run: php artisan test ${{ env.PHPUNIT_FLAGS }}